config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :users do
    resources :articles do
      resources :comments
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum:5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles,  dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_filter :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    # Add my attributes added to the devise User class
    #devise_parameter_sanitizer.for(:sign_up) << :first_name << :access
    devise_parameter_sanitizer.for(:account_update) << :first_name<< :access
    devise_parameter_sanitizer.for(:account_update) << :last_name<< :access
    devise_parameter_sanitizer.for(:account_update) << :about_me<< :access
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @articles = current_user.articles.all
  end

  def show
    @article = Article.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @article = current_user.articles.build
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to user_article_path(current_user.id, @article)
    else
      render 'new'
    end
  end

  def update
    @article = current_user.articles.find(params[:id])

    if @article.update(article_params)
      redirect_to user_article_path(current_user.id, @article)
    else
      render 'edit'
    end
  end

  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy

    redirect_to user_articles_path
  end



  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = current_user.articles.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to user_article_path(current_user.id, @article)
  end

  def destroy
    @article = current_user.articles.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to user_article_path(current_user.id, @article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.limit(5)
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for ([current_user, @article]) do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.error.full_message.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %><br>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, :class => "form-control", :rows => "20" %><br>
  </p>
  <p>
    <%= f.submit :class => "btn btn-primary" %><br>
  </p>
<% end %>

app/views/articles/edit.html.erb
<div class="col-md-5 col-sm-5 col-lg-5">

<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Back', user_articles_path, :class => "btn btn-primary" %>

</div>

app/views/articles/index.html.erb
<h1>
  Your Articles
  <%= link_to 'New Article', new_user_article_path, :class => "btn btn-success"%>
</h1>

<table class="table table-bordered">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th width="150px">Actions</th>
  </tr>
  <% unless @articles.count == 0 %>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td>
          <%= link_to 'Show', user_article_path(current_user.id, article)%>
          <%= link_to 'Edit', edit_user_article_path(current_user.id, article)%>
          <%= link_to 'Destroy', user_article_path(current_user.id, article), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="3" class="bold text-center">
        <h3>There are no articles!</h3>
      </td>
    </tr>
  <% end %>



</table>

app/views/articles/new.html.erb
<div class="col-md-5 col-sm-5 col-lg-5">
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', user_articles_path, :class => "btn btn-primary" %>

</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="col-md-4 col-sm-4 col-lg-4">
    <img src="http://vignette3.wikia.nocookie.net/p__/images/8/8c/Ruby_Jewel.png/revision/latest?cb=20140603161923&path-prefix=protagonist" class="image-responsive image-circle"><br>
    By: <%= @user.first_name %> <%= @user.last_name %>
  </div>
  <div class="col-md-8 col-sm-8 col-lg-8">
    <p>
      <h2><%= @article.title.capitalize %></h2>
    </p>
    <p>
      <%= @article.text %>
    </p>
    <div>
      <h4>Comments</h4>
      <p>
        <%= render @article.comments %>
      </p>
    </div>
    <div>
      <h5>Add a comment: </h5>
      <p>
        <%= render 'comments/form' %>
      </p>
    </div>
    <%= link_to 'Edit', edit_user_article_path(current_user.id, @article), :class => "btn btn-primary" %>
    <%= link_to 'Back', user_articles_path, :class => "btn btn-primary"  %>
  </div>
</div>

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.commenter %> says:</strong> <%= comment.body %>
</p>
<p>
  <%= link_to 'Destroy Comment', user_article_comment_path(current_user.id, @article.id, comment), method: :delete, data: {confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for ([current_user, @article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit :class => "btn btn-success" %>
  </p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Blog', root_path, :class => "navbar-brand" %>
    </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active">
            <%= link_to 'Home page', root_path %>
          </li>

        <% if user_signed_in? %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              My Articles
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'See all', user_articles_path(current_user) %>
              </li>
              <li>
                <%= link_to 'New Article', new_user_article_path(current_user) %>
              </li>
            </ul>
          </li>
        </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-cog"></span>
                Settings
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Account Settings', edit_user_registration_path %>
                </li>
                <li role="separtor" class="divider"></li>
                <li>
                  <%= link_to 'Sing out', destroy_user_session_path, :method => :delete %>
                </li>
              </ul>
            </li>
          </ul>
        <% else %>
        </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to 'Login', new_user_session_path%>
            </li>
            <li>
              <%= link_to 'Sign Up', new_user_registration_path %>
            </li>
          </ul>
        <% end %>

      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  <footer class="navbar navbar-default">
    <center>
      <div class="col-md-4 col-sm-4 col-lg-4">
        <p><span>About us</span></p>
        <p><span>Work with us</span></p>
        <p><span>Our Mission</span></p>
      </div>
      <div class="col-md-4 col-sm-4 col-lg-4">
        <p><span>maarclee@gmail.com</span></p>
        <p><span>facebook.com/marclerodrigues</span></p>
        <p><span>twitter.com/Maarclee</span></p>
      </div>
      <div class="col-md-4 col-sm-4 col-lg-4">
        <p><span>By Marcle Rodrigues</span><p>
        <p><span>All rights reserved</span><p>
        <p><span>github.com/marclerodrigues</span><p>
      </div>
    </center>
  </footer>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="centered_box">
  <h1>Blog</h1>
  <h3>make connections</h3>
</div>
<% unless @articles.count == 0 %>
  <% @articles.reverse.each do |article| %>
    <div class="col-md-4 col-sm-4 col-lg-4">
      <h1>
        <center>
          <%= article.title.capitalize %>
        </center>
      </h1>
      <span class="span">
      <% @user = @users.find(article.user_id) %>
        By: <%= @user.email %>, at <%= article.created_at %>
      </span>
      <%= link_to 'Read more...', user_article_path(@user, article)%>
    </div>
  <% end %>
<% else %>
  <center>
    <h2>There are no artiles on our platform!</h2>
  </center>

<% end %>